### ISSUE TITLE
PeriodFactor missing

### ISSUE THREAD

**Issue by arigon** [efento/NB-IoT-sensors-integration#2]
Hello

measurementPeriodFactor is missing in this example.
https://github.com/efento/NB-IoT-sensors-integration/blob/a00820f0dca15adefd95b46557c60d4fd9a92d24/NB-IoT-sensors-integration.py#L83

Best regards
Alex

**Comment by PawelTokarek** [comment]
Hello 
Try version higher than 1.2.1.
